http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  appconfig:
    host: localhost
    paths: ['/config','/config/*']
  appinvoice:
    host: localhost
    paths: ['/invoice','/invoice/*']
  apppay:
    host: localhost
    paths: ['/pay','/pay/*']
  apptransaction:
    host: localhost
    paths: ['/transaction','/transaction/*']
serviceEndpoints:
  appconfig:
    url: 'http://load-balancer/config/'
  appinvoice:
    url: 'http://load-balancer/invoice/'
  apppay:
    url: 'http://load-balancer/pay/'
  apptransaction:
    url: 'http://load-balancer/transaction/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - appconfig
      - apppay
      - apptransaction
      - appinvoice
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: appconfig
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false
          - action:
              serviceEndpoint: apppay
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false
          - action:
              serviceEndpoint: apptransaction
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false
          - action:
              serviceEndpoint: appinvoice
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false