apiVersion:   apps/v1
kind: Deployment
metadata:
  name: dredis
  namespace: work5
spec:
  replicas: 1
  selector:
    matchLabels:
         role: redis
  template:
    metadata:
      labels:
        role: redis
    spec:
     containers:
     - name: appredis
       image: redis
       ports:
        - containerPort: 6379

---

kind: Service
apiVersion: v1
metadata:
  name: cip
  namespace: work5
spec:
  selector:
    role: redis
  ports:
    - port: 6379
      targetPort: 6379
