apiVersion:   apps/v1
kind: Deployment
metadata:
  name: dapp
  namespace: work5
spec:
  replicas: 1
  selector:
    matchLabels:
         role: app
  template:
    metadata:
      labels:
        role: app
    spec:
     containers:
     - name: apppy
       image: cgironza/redishello:latest
       ports:
        - containerPort: 5000
       env:
        - name: REDIS_HOST
          value: $(CIP_SERVICE_HOST)

---

kind: Service
apiVersion: v1
metadata:
  name: lb
  namespace: work5
spec:
  type: LoadBalancer
  selector:
    role: app
  ports:
    - port: 5000
      targetPort: 5000
