apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: workshop5
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: underbedmonster/app:0.1.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
# Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
  namespace: workshop5
spec:
  selector:
    app: app
  type: LoadBalancer
  externalIPs:
  - 192.168.59.100
  ports:
    - name: http
      port: 8000
      targetPort: 8000