apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: intro-namespace
  labels:
   app: app
spec:
  selector:
    matchLabels:
         app: app
  template:
    metadata:
      labels:
        app: app
    spec: 
      containers:
      - name: app
        image: anamvgd/docker_intro:kube
        ports: 
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: intro-namespace
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000