---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: cnt-redis
          image: redis:latest
          ports:
           - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: rediswk5
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
