---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: python-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bryan-python          
  template:                     
    metadata:
      labels:                    
        app: bryan-python 
    spec:
      containers:
      - name: bryan-python
        image: bryanmv/bryan-python:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000      
---
apiVersion: v1
kind: Service                    
metadata:
  name: lbpython    
spec:
  type: LoadBalancer                 
  ports:                         
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: bryan-python 
