version: '3'

services:

  app-invoice:
    image: arturodiaz02/app-invoice:v2
    container_name: app-invoice
    platform: linux/amd64
    ports:
      - "8006:8006"
    networks:
      - distribuidos

  app-pay:
    image: arturodiaz02/app-pay:v1
    container_name: app-pay
    platform: linux/amd64
    ports:
      - "8010:8010"
    networks:
      - distribuidos

  app-transactions:
    image: arturodiaz02/app-transaction:v1
    container_name: app-transactions
    platform: linux/amd64
    ports:
      - "8082:8082"
    networks:
      - distribuidos

networks:
   distribuidos:
     external: true