apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-ns
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: li1408/compose:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: app-ns
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000