---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-counter-app
spec:
  replicas: 3 # Number of pods
  selector:
    matchLabels:
      app: python-counter-app
  template:
    metadata:
      labels:
        app: python-counter-app
    spec:
      containers:
      - name: python-counter-app
        image: camilaleniss/python-counter-app
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000 # As is defined in the Python app
---
apiVersion: v1
kind: Service
metadata:
  name: python-counter-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: python-counter-app
