---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: juancal97/pythonapp:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: python
