apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app-deploy
  namespace: w2
  labels:
   app: py-app
spec:
  replicas: 2 #Se que deberián ser 6 pero me traba el pc
  selector:
    matchLabels:
         app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
     containers:
     - name: py-app
       image: 'nelsonq2424/dockerpython2'
       ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
 name: py-app-service
 namespace: w2
 labels:
  app: py-app
spec:
 type: LoadBalancer
#  externalIPs:
#   - 192.168.49.2
 selector:
  app: py-app
 ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000