http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  app-config:
    host: localhost
    paths: ["/config", "/config/*"]
  app-invoice:
    host: localhost
    paths: ["/invoice", "/invoice/*"]
  app-pay:
    host: localhost
    paths: ["/pay", "/pay/*"]
  app-transaction:
    host: localhost
    paths: ["/transaction", "/transaction/*"]
serviceEndpoints:
  app-config:
    url: "http://loadbalancer/config/"
  app-invoice:
    url: "http://loadbalancer/invoice/"
  app-pay:
    url: "http://loadbalancer/pay/"
  app-transaction:
    url: "http://loadbalancer/transaction/"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - app-config
      - app-pay
      - app-transaction
      - app-invoice
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: app-config
              changeOrigin: true
              prependPath: false
              ignorePath: false
              stripPath: false
          - action:
              serviceEndpoint: app-pay
              changeOrigin: true
              prependPath: false
              ignorePath: false
              stripPath: false
          - action:
              serviceEndpoint: app-transaction
              changeOrigin: true
              prependPath: false
              ignorePath: false
              stripPath: false
          - action:
              serviceEndpoint: app-invoice
              changeOrigin: true
              prependPath: false
              ignorePath: false
              stripPath: false
