apiVersion: v1
kind: Service
metadata:
  name: redis-db
spec:
  selector:
    app: redis-bd
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-bd
  labels:
    app: redis-bd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-bd
  template:
    metadata:
      labels:
        app: redis-bd
    spec:
      containers:
      - name: redis-bd
        image: redis
        ports:
        - containerPort: 6379