apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: workshop
  replicas: 2
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      -  name: workshop
         image: workshop:local
         ports:
         - containerPort: 8000
