apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workshop
    matchExpressions:
      - {key: version, operator: In, values: ["0.1", "0.2"]}
  template:
    metadata:
      name: app
      labels:
        project: workshop5
        service: web
        version: "0.1"
    spec:
      containers:
      - name: workshop
        image: workshop:local
